### ISSUE TITLE
Using alipy with Tensorflow

### ISSUE THREAD

**Issue by sreevarsha** [NUAA-AL/ALiPy#2]
Hello, alipy  is unable to read the model I created using Tensorflow. I tried both creating a model and then reading it using AlExperiment and defining the model directly in the dialogs, both to no avail. Could you provide an example on how to rectify this/how to use Tensorflow models to be used for AL in your function please ? Any feedback would be greatly appreciated. Thanks !!!

**Comment by NUAA-AL** [comment]
Hi, sreevarsha.

If you want to use a Tensorflow model in AlExperiment class. You should pass a model object that accord scikit-learn api. You can re-encapsulate your model to achieve this. For example:
```
class my_model:

    def fit(X, y):
        my_own_training_function(...)

    def predict(X):
        my_own_predict_function(...)

    def predict_proba(X):
        my_own_proba_predict_function(...)
```

However, we suggest you to customize the whole active learning process instead of using AlExperiment due to the particularity of the model you are using. In this way, you can manage your model without any limitations. All you need to do is copy the example codes in the alipy_source_code_dir/examples/settings/query_instance.py, and replace the codes of model training/testing functions into your own functions (or replace any codes as you need). 

```
# Update model and calc performance according to the model you are using
model.fit(X=X[label_ind.index, :], y=y[label_ind.index])
pred = model.predict(X[test_idx, :])
```

For the model used in the instance selection function, there are 3 ways to using your own model:

1. Use `select(label_index, unlabel_index, model=None, batch_size=1)` if you are using sklearn model (or re-encapsulate your model to make it accord scikit-learn api).

```
model.fit(X[Lind.index], y[Lind.index])
select_ind = uncertainStrategy.select(Lind, Uind, batch_size=1, model=model)
```

It will using the given model object to get the necessary infomation from the unlabeled data. Note that, in most cases, the strategy may need the probabilistic output, so please make sure your model has the `predict_proba()` method.

2. Use the default logistic regression model to choose the instances by passing None to the model parameter. (It will train a logistic regression model from the labeled set for evaluating the unlabeled data.)

`select_ind = uncertainStrategy.select(Lind, Uind, batch_size=1, model=None)`

3. Use `select_by_prediction_mat()` by providing the probabilistic prediction matrix of your own model, shape is usually like [n_samples, n_classes]. (Some other types of output may be required according to different strategies, learn more in API reference.)

```
predict_result = my_model.get_prediction_of_data(X[Uind.index])
select_ind = QBCStrategy.select_by_prediction_mat(unlabel_index=Uind,
                                                  predict=predict_result,
                                                  batch_size=1)
```

Note that, not every strategy implements the `select_by_prediction_mat()`  methods. Also, the parameter requirements are different too. Please read the API reference before using each strategy.
